---
title: "pd101_text_intro_2"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

####The project
- This is a website about the korean show [Produce 101](https://www.google.com/search?q=Produce+101&oq=Produce+101&aqs=chrome..69i57j0j69i65l2j69i61j69i59.354j0j7&sourceid=chrome&ie=UTF-8).
- The main goal of my project is to explore which kind of trainees in the show are more likely to debut.
- Users can explore and interact with data about trainees' age, height, weight, training time, as well as their rankings and votes.

####Website layout
- About tab  
        - The website: the goal and layout of this website  
        - Kpop: a general introduction of Kpop for why am doing this project  
        - Produce 101: Description of the TV show  
        - Videos: Two videos from two seasons to visualize the show  
        - References: Weblinks of resources of my information and data  
- Trainee info tab  
        - Season 1 trainees: information table of season 1  
        - Season 2 trainees: information table of season 2   
        - Full data table: full trainee list and their information for exploration and download  
- Explore tab  
        - Single variable: Average age, height, weight and training time for trainees by gender    
        - Correlations: Correlation bewteen two variables (among age, evaluation1&2, ranking, height, weight, training time) presented in boxplot and grouped by gender  
        - Customize graph: Users can explore all data by choosing graph type (scatterplot/boxplot), x and y variables, whether to seperate by gender or whether to add linear model